language: java

# We need it because otherwise Travis CI injects an awkward './gradlew assemble' step into the CI workflow
install: true

jdk:
  - openjdk8
  - openjdk11

env:
  global:
    - GPG_FILE_NAME="starter.errors.gpg"
    - ENCRYPTED_GPG_FILE_NAME="starter.errors.gpg.enc"
    - # GPG_KEY_ID
    - secure: "Gsznm7+ZoE+mYPTrsOQZ2PsA00J3PBycPC/oXtMJpJmQrhAY4mN+aVsw6UmM2tuac/CLXsbvbjcwX6qdBOtA0c5Xyumqvhrzno7Ej2XUXLt11zvoetd7HXXeqSq4Tz/xO0gn0/TYCYuEt3AwjFvp5vbV2i1EexVZBbrOOH10rqTTixD9BjQBYWBbTVRJ0dzO/Jgyt/ee784v4wM0PGWeu5BJSeUQxS07zus5ShEZm3R4YaFwJyWQJ2CKW2CAhb9kPP60Rf3jkZdG/2ez/AD8SYnwkQl1WwsIDVhO+bV9CyuaHITNqiFsTPZ0ufiD7i/Qdk5DoPNdaf9Q9DQ/PWbRS87Kk47RWjSN4BtOO+HrCCrEpoAUKd0XHWDEwT62524nhS18f0q+7AtzA0u1T0g67AhwPnm/yTsXM8yYBzhQlsTJTiTo1giDuTsUfthkQsF/cx//x5/NvLoJfOwSo9fc+/lsIf7usH/EgHnBaCxIUUq5SHo4zefvwzJiKXUIw7xdMolLQNvQUlw0T5ZZED6YS4JF39aV4of6Z7fXbwjiAtQnxUBwWHS1NFqYftl0S0nsKbCOJ6EiMfJloCwJB1QA8mXt8SMm0PmvS9uJLO4o/k/yGCxuWflMSvLoF3QzoIhbUS1NBeedP55tjN7+UAm3D9oo+ZBKg9BiCLPSo+cAUjY="
    - # GPG_PASSPHRASE
    - secure: "Ox/FVXrmph2yh7vijWedxcQK6lxjcFr+QYAP6YkFtZkHJzUexO5oFAUztTtDl2xbPa1WmcgIEFmO5HeuNVqfAxQZkxbvwKjGv90oJkyN+Uccq9bAVHjJg4VYQ7lkstZiIHaHGg52Uv8+eR5ZT/9eu6CM9zLxIcVNSTzAAKuZiZyqc2yjSUgnh8TEjFl7AolwR6EuJRASSv66MH0BWO0wm2qMCy9B25bS7ntXBHiKpp0vtfDXi1hvL+hLR2IZYKvGJpi5ce/+liR3M74q7YJ25vlDLDNUDmT3sfGcCiqDoYQHW8/RR6Pp3gH3tCcMq81nz5GG6UINnTV4WPGApUfJUwVbOso95dhLc38eWZJfwFfMtojZNuOj1YINyzrVvrCiG/BXjIndW5QrqpLFsrSj1V4zBGWNNAZJgVkqKGzMSLQZLAxOnCmW6J2W7TSeh0WBIDUA6Aarm1Nl7bX3Q6jG1Iz+m4lIKIqzl4qj72B1jg0+vSXSSIjTrwbBKL16kHOhtyxp9dPxjNFMAVLrsbrPF+JfHXpqdaUM7gzwVUsj9/cIPbDJWnA0gk6O4NNs9/izXyBk/uQd1sBxeXzkLEz1KtLhIwT6xcN3R6h6KaaSnojw8+Hr9dMLuzH04mD9lPp/cKJEVQ6mKI6Kmlw8ApalXANEwAkLyz8wAecSEC5aAvk="
    - # PUBLISH_REPO_USERNAME
    - secure: "LGGS+dLtDKxx/V31yU3mtrAITT6LD5gxdUzLbc18YCnW68ki7CNwDq2VJh7491JbAInC4fMoVtnL23L5xJDMdBxChMHKdjV029KYdbZAqxuxDRlm5W/uvWkScNRJZ7vKeWkAX4KQimVxloMKyz59KvYoPtZSbevL62fxY9HtCUZ4k+EJhQGgMtZPFrC8BptrT3lnrxDBon+93e3T8HzUOs7hcAZpV865ljgZEH86CKXvodmHWW7Pj55J+M+9nG0rplni+SwnSqeAWUZiJktj/1ebnErQHqUG9ldH81ND68GaF2xxVlTz29/6ydtTC8J0OqICkADnFHfwMzPcf0AOKI6MlNfibPQDO/GrwFHJ7VCjgz9AS1lY6JUD5eWjJ+fkG0ANExrbi1MJRVem8CI2NIpA28Ds+kAHvoz3UNg5/gUE04eNmUJCl5UyNoqA0hkrpWzGg2XM55l/q2QJiLdFJISVz+2o3tVOaUE6suc6ybTqngqTrfCLMFAKr4y9b6LZlgzr2W5WOoWhyNam5/2pM7l191jJP4cYH+bTeiwrvIg2h4lgPGuxeUZWAiJljRDcyybXRnVtOs+63KTE135bmu6a7EKWX2s7+yahrWeOw1NgprlE3wZn8vk/l+TghTN/blXe/JvyhPktkWB3GSA3X2zXQLTy3AYm4714+Jc2+gQ="
    - # PUBLISH_REPO_PASSWORD
    - secure: "o3lDiwSsfw4Bud2r4Zg2NbZLLR+0Jzhebn/GTdwud2YmQ/qodZlZ0b4YhH/W0+PI7TXhPMn7aA87/LTTtuR549zB5XVjotADeRD7Lzmj6eq2efZiRrv0WIGfJjQ9BQ+NSGmUp3eXpD0GIywlp1gE71SjNiI24BsG96iEARy7QgB4FSSzm4uI0jbs0aqCrVi1oeiEM6/Ku+XIV5V1Yv9ysyGcdlnu1kH7YcVCBhdUCAyj532OZGiNvYjir1YzDlnFBScN4HsOssFa75GnyWE2c6gNo1KLFFvRGjVFtcsQoaNCtemPD6/kqbWzN5rTEYM7tQNXjZLxMcIeLhCh31C/BaO4KO4ANg7inKOaX+zdKCXGdDuDNwJl+7oWcTkKbPBy4rpPEqSa217kXzs0SXAQ1D36lFVTpNKlgfuKGl891GnQGOTwzDK/IFjKfSAFhjFfJIiKcdAF9QYIXsVZKuuAXAhlXfl+gmv0v7MOEZjn4vo3yl0iWXAcaKCBQVbH6pI3xlzwzqaooseJWAH6XteJmZ6R+zjk9iCNQvSf05wezQei3Tww7g8bW47u4+/GKMjubbn4sRhz5H7/mh+RFdxWc1+QwdZWdOBS7ZuMJQVUu05lnwDU5KlpETw6FxoSXroc+3XXNG7fOLYqMXbGYrY4ws+uYl4DQZdEtrmc0Zg8BM4="
    - # PUBLISH_SNAPSHOT_REPO_URL
    - secure: "PG+xowu4t6xplItUy68dhqQwC1yqIrDYIFqN0lV3Y3YEk1sxNHdyctUogghfjJLV/RlmxstBbTjLzoH290XIKFJf+9bI8higcvbxA+dkOzOwhKgvV3ZZNV5tNyr6BByWvXOrAEqgEyTJZ2u2zc8uor3GeeorqMBvSRi/fagRHI5/Wr3my3jB95MwHZ4SKwycIQgG2TGfznTuUV0P8RlVbBblvfIfuQWy/8pmWJTbHGO4LJ+uvnv488o4C2KVWpqoiMdRivBnQqQaubIng29wmwQwlOGgXRBgmKn2O5Ej6AtLXetEOrY6NguE00ZlcsIpfmOPhAIV1UWVE2EjMJL3hyWP0t7IFh6EDPh3i1W77gGOn0MGaKUndeBywqnCFyoKM5AGjunUv9YeveEzmI3tbYeO5kTkWpB4n6psehZI2bg8iYP7f8yocPsV1YGWe0DaT+w3UFczfCZgOXNcdD21deO6YoDYEg5Z8syuG3iJASimLKkzmrOThE5ANKQHhxvQJty31dnQ8QST+r6NgcAMeKJbqwC7BvnNsvfTT1OPei/c33x1iYfjYVnP1bVCJvYhvBk3iFn9h8mndZYAVwIKLxt9sl8MGjfigJ0PhtK4thkH83Uhkkf/099F2vr4DAGtS+w7a1kqRzfJxZhnfPfkU1x78auaCV8sFitiIcRWOc4="
    - # PUBLISH_RELEASE_REPO_URL
    - secure: "V2jrWqvR/0tThnVzh0fKdn0PruFF8+OKCbOx5DQOizMTKTTO7HSI/ke/3s82Oflm0MH2gOWIP6Njhl1IIU3kAFc2g9TUWiQpdX8syR73RVogg+gLRnFNh9ESbzicR8C1vIa84YKeV0GgQss19XJLgdurOuQaIvF2Fjmu+h764L9nJzF7Z14Fu0hd/oV1KYm1yqL8E13RR4byebz5bd26CwPTe82dk/JZHnxsWDo+8xcW5d8aMxEM7sfDFcRdyxSGQo+eA9Y5lRIw+tkP96F1c5kTyZUZ8mmnYqygf4+tWs2fL22jlveSS4qOXrPkeNdOg+EowlJz6551RMdDM2qsWlReF/bWbPpRt29IFbwBljKo5NV7viVpvUihXyDm5hMCl/XD7biTJ/trfLj/BqVw0q8HIj8jzufqkgyxLMVI3e+ipZWxEtRtrw0ln/FXlsa+JwMtdHPVPA4FNCZRkiAlnOlUM9cLhQQzjUthbcr2jiJO9tynj87r9v9h91aHPtCkgLRzfGWhiib+z9GBAZdsa9sxQqj4gL4iRgY/13QpZasi8FO56RgGcu356h75Psh2ctznbnvTrZ1dKjTV0KyPKb51KsSnfX5K/1QqlDqLvkjVsgZ+0KcTzu9HLQhowm/QxWNBddc+wL+WwrGmyAP0rEmVZezF5k2ra1ufZzZqYCM="

before_script:
  - chmod -R ug+x .travis

script: .travis/build.sh

jobs:
  include:
    - stage: deploy
      name: Deploy Snapshot
      jdk: openjdk11
      if: |
        branch = master AND \
        type = push
      script: .travis/deploy.sh
    - stage: deploy
      name: Deploy Release
      if: tag IS present AND tag =~ ^(\d)+\.(\d)+(\.(\d)+)*(-[\w]+)*$
      script: .travis/deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: FhtlDhO7gwVw5yHB2VPDFhCJXNXCT5666k4D9nB0baOUMJm+YYZ73FD6kRNL138TEQuWHjV5yCjw3Ni8MRGqy9MOfQg904GYlcKdp+sCFoPGKSmxHq0Ov9eR/Qpuh8EbdasjCIyx49UCurXyZ7I4Hvt0LPhslDS5BJJwc1+/Os8y0MxNVnuriXO4i5Qst5CXwVqMDheytHaBpmcfZXEmmXO+YSgimVcpn2plkph1jjdVDKM7/45ZueEduJ3Y3U/zVA2VjHL6vxORG2EIYAaVMTQeRoIUj5b/3AVVtvTML1qrinHAB4FfOnUe6TlLSaC9YPdDS0uXfEGhDVzAn2wj12My8S2qLDq0hhcN8hBA0rxRwaTpDHOjgQ0aw7d1VnT6Jvf4Lvhkek4b8/i2MWQ+/17m3Hds6iHlm0WCfxnn5ly83nVsCs/vUWhbHb5PHSjE2EgavQ45T4uIwOIlhSIBkWHiNYY5LhHrJD5c4JQNWEa40LnRQ+6OPaRsgyGSsVgCZvYJuYQXVbvJiF0C82SZ9qUvZE2Nlmb8CEglGo6PqqA5Ew9TbHnP5jL3y6qv3cGl8uUmZypCLSPtaHvuhJjk+6aBULpzXGeEIPIP/vfg7rFJMELG6dq7FqBaRmDqBTeWdGKsU+cSF8xelgNzJS3sJux0iO//gxaQ04MNzGgjrik=
        file: "$TRAVIS_BUILD_DIR/build/libs/*"
        body: "Release of $TRAVIS_TAG"
        skip_cleanup: true
        draft: true
        on:
          repo: ekino/spring-boot-starter-errors
          tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
