name: Build branch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 13 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: ./gradlew build
